#!/usr/bin/env tsx
/**
 * 自动生成 MCP Tools 的 TypeScript 类型定义
 * 
 * 完全基于运行时 toolRegistry 数据生成类型，不读取源码
 * 参考 mcp.middleware.ts 的实现方式
 * 
 * 对于复杂的递归 schema（z.lazy），从 schema 文件中扫描并导入已定义的类型
 */

import * as fs from 'fs';
import * as path from 'path';
import * as glob from 'glob';
import { scanToolsFromRegistry, ExtendedToolInfo } from './tool-utils';

interface ToolInfo {
    toolName: string;
    methodName: string;
    title?: string;
    description?: string;
    paramsTypeName: string;
    resultTypeName: string;
}

/**
 * Schema 到 Type 的映射
 * 从 schema 文件中扫描 SchemaXxx -> TXxx 的映射关系
 */
interface SchemaTypeMapping {
    schemaName: string;  // 例如: SchemaCreatedAssetResult
    typeName: string;    // 例如: TCreatedAssetResult
    importPath: string;  // 例如: ../../dist/api/assets/schema
}

/**
 * 扫描所有 schema 文件，建立 Schema 到 Type 的映射
 * 查找所有 export type TXxx = z.infer<typeof SchemaXxx> 的定义
 */
function scanSchemaTypeMappings(): Map<string, SchemaTypeMapping> {
    const mappings = new Map<string, SchemaTypeMapping>();
    
    // 查找所有 schema 文件（以 schema 结尾的 ts 文件）
    const schemaFiles = glob.sync('src/api/**/*schema*.ts', {
        absolute: true,
    });

    for (const schemaFile of schemaFiles) {
        const content = fs.readFileSync(schemaFile, 'utf-8');
        
        // 匹配 export type TXxx = z.infer<typeof SchemaXxx>
        const inferPattern = /export\s+type\s+(T\w+)\s*=\s*z\.infer<typeof\s+(Schema\w+)>/g;
        let match;
        
        while ((match = inferPattern.exec(content)) !== null) {
            const typeName = match[1];
            const schemaName = match[2];
            
            // 计算导入路径（从 e2e/types 到 dist/api/xxx/schema）
            const distPath = schemaFile
                .replace(/\\/g, '/')
                .replace(/^.*\/src\//, 'dist/')
                .replace(/\.ts$/, '');
            const importPath = path.relative(
                path.resolve(process.cwd(), 'e2e/types'),
                path.resolve(process.cwd(), distPath)
            ).replace(/\\/g, '/');
            
            mappings.set(schemaName, {
                schemaName,
                typeName,
                importPath,
            });
        }
    }
    
    return mappings;
}

/**
 * 生成 TypeScript 类型定义
 */
function generateTypeDefinitions(tools: ToolInfo[], typeBlocks: string[], importsByPath: Map<string, Set<string>>): string {
    const lines: string[] = [];

    // 文件头部
    lines.push('/**');
    lines.push(' * MCP Tools Type Definitions');
    lines.push(' * ');
    lines.push(' * 🤖 This file is auto-generated by e2e/scripts/generate-mcp-types.ts');
    lines.push(' * DO NOT EDIT MANUALLY');
    lines.push(' * ');
    lines.push(' * To regenerate: npm run generate:mcp-types');
    lines.push(' * ');
    lines.push(' * 基于运行时 toolRegistry 数据生成，完全使用 zod-to-ts 从 Zod Schema 转换');
    lines.push(' */');
    lines.push('');

    // MCP Response 类型
    lines.push('// MCP Response wrapper');
    lines.push('export interface MCPResponse<T = any> {');
    lines.push('    code: number;');
    lines.push('    data: T;');
    lines.push('    reason?: string;');
    lines.push('}');
    lines.push('');

    // 生成导入语句（如果有从 schema 文件导入的类型）
    if (importsByPath && importsByPath.size > 0) {
        lines.push('// Import types from schema files (for complex recursive schemas)');
        for (const [importPath, types] of importsByPath.entries()) {
            const typeList = Array.from(types).sort();
            if (typeList.length === 1) {
                lines.push(`import type { ${typeList[0]} } from '${importPath}';`);
            } else {
                lines.push(`import type {`);
                typeList.forEach(type => {
                    lines.push(`    ${type},`);
                });
                lines.push(`} from '${importPath}';`);
            }
        }
        lines.push('');
    }

    // 添加从 zod-to-ts 生成的类型块，并确保它们都是 export type
    if (typeBlocks.length > 0) {
        lines.push('// Tool parameter and result types (generated from Zod schemas)');
        lines.push('// These types are automatically generated from runtime Zod schemas using zod-to-ts');
        lines.push('// DO NOT manually edit these type definitions');
        lines.push('');
        typeBlocks.forEach(block => {
            // 将 type 改为 export type，确保类型可以被导出使用
            // 使用多行匹配，处理可能的多行 type 定义
            // 匹配模式：行首的 "type " 替换为 "export type "
            let exportedBlock = block.replace(/^type\s+/gm, 'export type ');
            // 将双引号替换为单引号（zod-to-ts 默认使用双引号）
            exportedBlock = exportedBlock.replace(/"/g, "'");
            lines.push(exportedBlock);
            lines.push('');
        });
    }

    // 生成工具映射表
    lines.push('/**');
    lines.push(' * MCP Tools 类型映射表');
    lines.push(' * ');
    lines.push(' * 使用方式：');
    lines.push(' * ```typescript');
    lines.push(' * const result = await mcpClient.callTool(\'assets-create-asset\', {');
    lines.push(' *   options: { target: \'db://assets/test.txt\' }');
    lines.push(' * });');
    lines.push(' * // result 的类型会自动推断为 MCPResponse<AssetsCreateAssetResult>');
    lines.push(' * ```');
    lines.push(' */');
    lines.push('export interface MCPToolsMap {');

    tools.forEach(tool => {
        if (tool.title || tool.description) {
            lines.push('');
            lines.push('    /**');
            if (tool.title) {
                lines.push(`     * ${tool.title}`);
            }
            if (tool.description) {
                lines.push(`     * ${tool.description}`);
            }
            lines.push('     */');
        }

        // 直接使用 zod-to-ts 生成的类型名称
        const paramType = tool.paramsTypeName;
        const returnType = tool.resultTypeName;

        lines.push(`    '${tool.toolName}': {`);
        lines.push(`        params: ${paramType};`);
        lines.push(`        result: ${returnType};`);
        lines.push('    };');
    });

    lines.push('}');
    lines.push('');

    // 工具名称联合类型
    lines.push('// Tool name union type');
    lines.push('export type MCPToolName = keyof MCPToolsMap;');
    lines.push('');

    // 导出工具列表（方便运行时使用）
    lines.push('// Available tools list');
    lines.push('export const MCP_TOOLS: MCPToolName[] = [');
    tools.forEach(tool => {
        lines.push(`    '${tool.toolName}',`);
    });
    lines.push('];');
    lines.push('');

    // 统计信息
    lines.push('/**');
    lines.push(' * 生成统计:');
    lines.push(` * - 总工具数: ${tools.length}`);
    lines.push(` * - 生成时间: ${new Date().toISOString()}`);
    lines.push(' */');

    return lines.join('\n');
}

/**
 * 将 kebab-case 转换为 PascalCase
 */
function toPascalCase(str: string): string {
    return str
        .split('-')
        .map(word => word.charAt(0).toUpperCase() + word.slice(1))
        .join('');
}

/**
 * 基于运行时注册信息（Zod Schema）直接生成 TS 类型定义
 * 完全参考 mcp.middleware.ts 的实现方式，使用 zod-to-ts 从 schema 生成类型
 * 对于复杂的递归 schema，尝试从 schema 映射中查找对应的类型名称
 */
async function generateTypesFromRuntimeSchemas(
    tools: ExtendedToolInfo[],
    schemaMappings: Map<string, SchemaTypeMapping>
): Promise<{ tools: ToolInfo[]; typeBlocks: string[]; importsByPath: Map<string, Set<string>> }> {
    const { z } = await import('zod');
    // @ts-ignore - zod-to-ts v1.1.4 可能没有完整的类型定义
    const { zodToTs, printNode, createTypeAlias } = await import('zod-to-ts');
    
    const resultTools: ToolInfo[] = [];
    const allTypeBlocks: string[] = [];
    const importsByPath = new Map<string, Set<string>>();

    for (const tool of tools) {
        const typeBlocks: string[] = [];
        let paramsTypeName = 'Record<string, never>';
        let resultTypeName = 'any';

        // 从 paramSchemas 构建输入 schema（参考 mcp.middleware.ts:78-85）
        if (tool.paramSchemas && tool.paramSchemas.length > 0) {
            try {
                const typeName = toPascalCase(tool.toolName) + 'Params';
                
                // 构建输入对象 schema（与 mcp.middleware.ts 中的逻辑完全一致）
                const inputSchemaFields: Record<string, any> = {};
                tool.paramSchemas
                    .sort((a, b) => a.index - b.index)
                    .forEach((param) => {
                        if (param.name) {
                            inputSchemaFields[param.name] = param.schema;
                        }
                    });

                // 如果有字段，构建 z.object schema
                if (Object.keys(inputSchemaFields).length > 0) {
                    const inputSchema = z.object(inputSchemaFields);
                    // zod-to-ts v1.1.4 API: zodToTs(schema, typeName) 返回 { node, store }
                    const { node } = zodToTs(inputSchema, typeName);
                    // 创建类型别名
                    const typeAlias = createTypeAlias(node, typeName);
                    typeBlocks.push(printNode(typeAlias));
                    paramsTypeName = typeName;
                }
            } catch (error) {
                console.warn(`⚠️  生成 ${tool.toolName} Params 类型失败:`, error);
                paramsTypeName = 'Record<string, never>';
            }
        }

        // 生成 Result 类型（参考 mcp.middleware.ts:88）
        // 注意：returnSchema 已经被 createCommonResult 包装，包含 { code, data, reason }
        // 但 MCPResponse 已经包装了这些字段，所以我们需要提取 data 字段的类型
        if (tool.returnSchema) {
            try {
                const typeName = toPascalCase(tool.toolName) + 'Result';
                
                // 尝试从 returnSchema 中提取 data 字段的 schema
                // returnSchema 是 createCommonResult(originalSchema) 的结果
                // 结构是: { code: ..., data: originalSchema | undefined, reason: ... }
                let dataSchema: any = tool.returnSchema;
                
                // 如果 returnSchema 是 z.object，尝试提取 data 字段
                if (tool.returnSchema && typeof tool.returnSchema === 'object' && '_def' in tool.returnSchema) {
                    const def = (tool.returnSchema as any)._def;
                    // 检查是否是 z.object
                    if (def && def.typeName === 'ZodObject') {
                        const shape = def.shape();
                        if (shape && shape.data) {
                            // 提取 data 字段的 schema
                            dataSchema = shape.data;
                            // data 可能是 z.union([originalSchema, z.undefined()])
                            // 需要提取 union 中的第一个元素（原始 schema）
                            if (dataSchema && dataSchema._def && dataSchema._def.typeName === 'ZodUnion') {
                                const options = dataSchema._def.options;
                                if (options && options.length > 0) {
                                    // 找到第一个不是 undefined 的选项
                                    dataSchema = options.find((opt: any) => 
                                        opt._def && opt._def.typeName !== 'ZodUndefined'
                                    ) || options[0];
                                }
                            }
                        }
                    }
                }
                
                // 处理 z.lazy() schema：展开它
                if (dataSchema && dataSchema._def && dataSchema._def.typeName === 'ZodLazy') {
                    try {
                        // 调用 getter 函数展开 lazy schema
                        dataSchema = dataSchema._def.getter();
                    } catch {
                        // 如果展开失败，使用 any，但继续处理该工具
                        console.warn(`⚠️  ${tool.toolName} Result 类型展开 lazy schema 失败，使用 any`);
                        resultTypeName = 'any';
                        // 不 continue，继续处理该工具
                    }
                }
                
                // 处理 z.nullable()：提取内部类型
                if (dataSchema && dataSchema._def && dataSchema._def.typeName === 'ZodNullable') {
                    dataSchema = dataSchema._def.innerType;
                }
                
                // 只有在 resultTypeName 还是初始值 'any' 时才尝试生成类型
                // 如果之前已经设置为 'any'（因为 lazy schema 展开失败），则跳过类型生成
                if (resultTypeName === 'any' && dataSchema && dataSchema._def && dataSchema._def.typeName === 'ZodLazy') {
                    // lazy schema 展开失败，已经设置为 any，跳过类型生成
                } else if (resultTypeName !== 'any' || !dataSchema || !dataSchema._def || dataSchema._def.typeName !== 'ZodLazy') {
                    // 使用提取的 dataSchema 生成类型
                    try {
                        const { node } = zodToTs(dataSchema, typeName);
                        // 创建类型别名
                        const typeAlias = createTypeAlias(node, typeName);
                        const generatedType = printNode(typeAlias);
                        
                        // 检查是否有循环引用（类型名称出现在类型定义中）
                        const typeDefMatch = generatedType.match(/type\s+(\w+)\s*=\s*(.+);/s);
                        if (typeDefMatch) {
                            const [, typeNameInDef, typeBody] = typeDefMatch;
                            // 如果类型体只包含类型名称本身（循环引用），使用 any
                            if (typeBody.trim() === typeNameInDef || 
                                typeBody.trim() === `${typeNameInDef} | null` ||
                                typeBody.trim() === `${typeNameInDef}[]`) {
                                console.warn(`⚠️  ${tool.toolName} Result 类型存在循环引用，使用 any`);
                                resultTypeName = 'any';
                                // 不添加类型块，继续处理该工具，确保工具被添加到结果中
                            } else {
                                // 类型生成成功，添加到类型块中
                                typeBlocks.push(generatedType);
                                resultTypeName = typeName;
                            }
                        } else {
                            // 无法解析类型定义，直接使用生成的类型
                            typeBlocks.push(generatedType);
                            resultTypeName = typeName;
                        }
                    } catch (genError) {
                        console.warn(`⚠️  生成 ${tool.toolName} Result 类型失败:`, genError);
                        resultTypeName = 'any';
                    }
                }
            } catch (error) {
                console.warn(`⚠️  生成 ${tool.toolName} Result 类型失败:`, error);
                resultTypeName = 'any';
            }
        }

        resultTools.push({
            toolName: tool.toolName,
            methodName: tool.methodName,
            title: tool.title,
            description: tool.description,
            paramsTypeName,
            resultTypeName,
        });

        allTypeBlocks.push(...typeBlocks);
    }

    return { tools: resultTools, typeBlocks: allTypeBlocks, importsByPath };
}

/**
 * 主函数
 * 完全基于运行时 toolRegistry 数据生成类型，不读取源码
 */
async function main() {
    console.log('🤖 开始生成 MCP Tools 类型定义（基于运行时数据）...\n');

    // 步骤 1: 使用 toolRegistry 扫描已注册的工具（参考 mcp.middleware.ts）
    console.log('🔍 扫描 MCP API 工具定义 (通过 toolRegistry)...\n');
    const toolsFromRegistry = await scanToolsFromRegistry();
    console.log(`✅ 找到 ${toolsFromRegistry.length} 个 MCP 工具\n`);

    // 步骤 2: 扫描 schema 文件，建立映射（用于处理循环引用）
    const schemaMappings = scanSchemaTypeMappings();

    // 步骤 3: 基于运行时 Zod Schema 生成 TS 类型（参考 mcp.middleware.ts 的实现）
    console.log('📝 从 Zod Schema 生成 TypeScript 类型...\n');
    const { tools, typeBlocks, importsByPath } = await generateTypesFromRuntimeSchemas(toolsFromRegistry, schemaMappings);
    console.log(`✅ 生成了 ${typeBlocks.length} 个类型定义块\n`);

    // 步骤 4: 生成完整的类型定义文件
    console.log('📄 生成类型定义文件...\n');
    const typeDefinitions = generateTypeDefinitions(tools, typeBlocks, importsByPath);

    // 步骤 4: 写入文件
    const outputPath = path.resolve(process.cwd(), 'e2e/types/mcp-tools.generated.ts');
    const outputDir = path.dirname(outputPath);

    if (!fs.existsSync(outputDir)) {
        fs.mkdirSync(outputDir, { recursive: true });
    }

    fs.writeFileSync(outputPath, typeDefinitions, 'utf-8');
    console.log(`✨ 类型定义已生成: ${path.relative(process.cwd(), outputPath)}\n`);
}

// 运行脚本
main().catch(error => {
    console.error('❌ 生成失败:', error);
    process.exit(1);
});

